[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.chat"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] // TODO: Add keywords
icon = "icon.png" // TODO: Add icon path
repository = "https://github.com/ballerina-platform/sample-ballerina-connector-repo"

[build-options]
observabilityIncluded = true